const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let x={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x.message||x.error||`HTTP ${r.status}`);return x}
function showDash(ok){$('#loginCard').classList.toggle('hidden',ok);$('#dashboard').classList.toggle('hidden',!ok);$('#logout').classList.toggle('hidden',!ok)}
async function session(){try{await api('/api/admin/session');showDash(true);await Promise.all([loadUsers(),loadActivity()])}catch{showDash(false)}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMsg').textContent='Signing in…';try{await api('/api/admin/session',{method:'POST',body:JSON.stringify({secret:$('#adminSecret').value})});$('#adminSecret').value='';$('#loginMsg').textContent='';showDash(true);await Promise.all([loadUsers(),loadActivity()])}catch(err){$('#loginMsg').textContent=err.message}});
$('#logout').onclick=async()=>{try{await api('/api/admin/session',{method:'DELETE'})}catch{}showDash(false)};
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();$('#createMsg').textContent='Creating…';try{await api('/api/admin/users',{method:'POST',body:JSON.stringify({username:$('#newUsername').value,password:$('#newPassword').value,valid_from:$('#validFrom').value,valid_until:$('#validUntil').value})});$('#createMsg').textContent='User created.';$('#newUsername').value='';$('#newPassword').value='';await Promise.all([loadUsers(),loadActivity()])}catch(err){$('#createMsg').textContent=err.message}});
async function loadUsers(){const x=await api('/api/admin/users');const tb=$('#usersBody');tb.innerHTML=x.users.map(u=>`<tr><td><b>${esc(u.username)}</b></td><td><span class="pill ${u.status==='active'?'active':'disabled'}">${esc(u.status)}</span></td><td>${esc(u.validFrom)} → ${esc(u.validUntil)}</td><td>${u.deviceBound?`BOUND<br><small>${esc(u.device?.deviceName||u.device?.deviceId||'Authorized PC')}</small>`:'Not bound'}</td><td>${u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'—'}</td><td><div class="actions"><button onclick="act('${esc(u.username)}','${u.status==='active'?'disable':'enable'}')">${u.status==='active'?'Disable':'Enable'}</button><button onclick="dates('${esc(u.username)}','${esc(u.validFrom)}','${esc(u.validUntil)}')">Dates</button><button onclick="passwordReset('${esc(u.username)}')">Password</button><button onclick="act('${esc(u.username)}','reset_device')">Reset Device</button><button class="danger" onclick="removeUser('${esc(u.username)}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No users yet.</td></tr>'}
window.act=async(username,action)=>{if(action==='reset_device'&&!confirm(`Reset authorized device for ${username}?`))return;try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({username,action})});await Promise.all([loadUsers(),loadActivity()])}catch(e){alert(e.message)}};
window.dates=async(username,from,until)=>{const a=prompt('Valid From (YYYY-MM-DD)',from);if(!a)return;const b=prompt('Valid Until (YYYY-MM-DD)',until);if(!b)return;try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({username,action:'set_dates',valid_from:a,valid_until:b})});await Promise.all([loadUsers(),loadActivity()])}catch(e){alert(e.message)}};
window.passwordReset=async username=>{const p=prompt(`New password for ${username} (minimum 10 characters)`);if(!p)return;try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({username,action:'reset_password',password:p})});alert('Password reset. Existing sessions revoked.');await loadActivity()}catch(e){alert(e.message)}};
window.removeUser=async username=>{if(!confirm(`Permanently delete ${username}?`))return;try{await api('/api/admin/user-action',{method:'POST',body:JSON.stringify({username,action:'delete'})});await Promise.all([loadUsers(),loadActivity()])}catch(e){alert(e.message)}};
async function loadActivity(){const x=await api('/api/admin/activity');$('#activity').innerHTML=x.activity.map(a=>`<div class="event"><b>${esc(a.type)}</b> • ${esc(a.username||'system')}<br><small>${new Date(a.createdAt).toLocaleString()}</small></div>`).join('')||'No activity yet.'}
$('#refresh').onclick=loadUsers;$('#activityRefresh').onclick=loadActivity;
const d=new Date();const iso=d.toISOString().slice(0,10);$('#validFrom').value=iso;const e=new Date(d);e.setDate(e.getDate()+30);$('#validUntil').value=e.toISOString().slice(0,10);session();
