(()=>{
'use strict';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function ensureLegacyTargets(){if(!$('#mapDiv')){const el=document.createElement('span');el.id='mapDiv';el.hidden=true;document.body.appendChild(el)}}
function repairVisibleText(){const b=$('.bismillah');if(b)b.textContent='بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ';}
function activateAnalysisTab(name){$$('#analysisTabs button').forEach(btn=>btn.classList.toggle('activeTab',btn.dataset.tab===name));$$('.tabPane').forEach(p=>p.classList.toggle('activePane',p.dataset.pane===name))}
function installAnalysisTabs(){const tabs=$('#analysisTabs');if(!tabs)return;$$('#analysisTabs button').forEach(btn=>btn.type='button');tabs.addEventListener('click',e=>{const btn=e.target.closest('button[data-tab]');if(btn)activateAnalysisTab(btn.dataset.tab)})}
function cleanAnalysisError(){const el=$('#explanation');if(!el)return;const txt=String(el.textContent||'');const cleaned=txt.replace(/\s*Response:\s*map\[[^\]]*\]\.?\s*$/i,'').trim();if(cleaned!==txt)el.textContent=cleaned}
function watchAnalysisUpdates(){const targets=['#signalCard','#explanation','#topSetups','#buyScoreTop','#sellScoreTop'].map($).filter(Boolean);if(!targets.length)return;let timer=0;const refresh=()=>{clearTimeout(timer);timer=setTimeout(cleanAnalysisError,20)};const observer=new MutationObserver(refresh);targets.forEach(t=>observer.observe(t,{subtree:true,childList:true,characterData:true,attributes:true}));window.__mhRuntimeDetailsObserver=observer;cleanAnalysisError()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function impactClass(v){const s=String(v||'').trim().toLowerCase();if(s.includes('high'))return'high';if(s==='low')return'low';return'medium'}
function isAllowedImpact(v){const s=String(v||'').trim().toLowerCase();return s==='high'||s==='medium'||s==='med'||s==='low'}
function eventMeta(e){const parts=[];if(e.actual)parts.push(`Act: ${esc(e.actual)}`);if(e.forecast)parts.push(`Fcst: ${esc(e.forecast)}`);if(e.previous)parts.push(`Prev: ${esc(e.previous)}`);return parts.join(' • ')}
async function loadEconomicCalendar(){const host=$('#mhEconomicCalendar');if(!host)return;try{const r=await fetch('/api/economic-calendar',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();const rawDays=Array.isArray(data.days)?data.days:[];const days=rawDays.map(day=>({...day,events:(Array.isArray(day.events)?day.events:[]).filter(e=>isAllowedImpact(e.impact))})).filter(day=>day.events.length>0).slice(0,3);if(!days.length){host.innerHTML='<div class="mhCalEmpty">No Low / Medium / High economic events found for the current or next available dates.</div>';return}host.innerHTML=days.map((day,idx)=>`<section class="mhCalDay" data-day-index="${idx+1}"><div class="mhCalDate"><span>${esc(day.label||day.date)}</span><small>DAY ${idx+1} / ${days.length}</small></div>${day.events.map(e=>`<div class="mhCalEvent"><div class="mhCalTime">${esc(e.time)}</div><div class="mhCalImpact ${impactClass(e.impact)}">${esc(String(e.impact||'Medium').replace(/^med$/i,'Medium'))}</div><div class="mhCalBody"><div class="mhCalTitle">${esc(e.title||'Economic event')}</div><div class="mhCalMeta">${eventMeta(e)}</div></div><div class="mhCalCountry">${esc(e.country)}</div></div>`).join('')}</section>`).join('');host.scrollTop=0}catch(e){host.innerHTML='<div class="mhCalEmpty">Economic calendar is temporarily unavailable.</div>'}}
function installEconomicCalendar(){const crop=$('.calendarCrop');if(!crop)return;crop.innerHTML='<div id="mhEconomicCalendar" class="mhCalendarScroll"><div class="mhCalEmpty">Loading date-based Low / Medium / High economic calendar…</div></div>';loadEconomicCalendar();setInterval(loadEconomicCalendar,3*60*1000)}
function boot(){ensureLegacyTargets();repairVisibleText();installAnalysisTabs();watchAnalysisUpdates();installEconomicCalendar()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
